### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by Miminepho** [oilbeater/oilbeater#1]
Hello :)

Thanks for the [great article](https://oilbeater.com/en/2024/02/22/minikube-vs-kind-vs-k3d/) about minikube vs kind vs k3d.

Just wanted to let you know that the word "Performance" is misspelled in README.md: "I’m currently learning AI and **Perfromance**"

**Comment by oilbeater** [comment]
Thanks for reading :) @anhminhpho
